[2025-03-02 22:52:48 ERROR (JavaFX Application Thread)] - Error switching to main screen: Error resolving onAction='#onHelloButtonClick', either the event handler is not in the Namespace or there is an error in the script.
/home/dnd/IdeaProjects/attt-client/target/classes/org/duynguyen/atttclient/main.fxml:15

[2025-03-15 01:18:59 ERROR (Thread-1)] - java.net.ConnectException: Connection refused
[2025-03-15 15:37:00 ERROR (Thread-1)] - java.net.ConnectException: Connection refused
[2025-03-15 15:47:34 ERROR (Thread-1)] - java.net.ConnectException: Connection refused
[2025-03-15 16:59:02 ERROR (Thread-1)] - java.net.ConnectException: Connection refused
[2025-03-15 21:29:42 ERROR (Thread-1)] - java.net.ConnectException: Connection refused
[2025-03-15 21:51:47 ERROR (Thread-3)] - messageNotLogin: Index 2 out of bounds for length 2
[2025-03-15 21:55:11 ERROR (Thread-3)] - messageNotLogin: Index 2 out of bounds for length 2
[2025-03-15 22:05:59 ERROR (Thread-3)] - messageNotLogin: Index 2 out of bounds for length 2
[2025-03-15 22:06:10 ERROR (Thread-3)] - messageNotLogin: Index 2 out of bounds for length 2
[2025-03-16 13:07:40 ERROR (Thread-1)] - java.net.ConnectException: Connection refused
[2025-03-16 13:21:09 ERROR (Thread-3)] - Lỗi khi chuẩn bị nhận file: Downloads/094edcf1-7976-4c65-9dc1-87df8dc24e78.des (No such file or directory)
[2025-03-16 14:03:54 ERROR (Thread-3)] - messageNotLogin: null
[2025-03-16 14:05:16 ERROR (Thread-3)] - messageNotLogin: null
[2025-03-16 14:06:45 ERROR (Thread-3)] - messageNotLogin: null
[2025-03-16 14:11:50 ERROR (Thread-3)] - message not auth: null
[2025-03-16 14:14:22 ERROR (Thread-3)] - message not auth: null
[2025-03-16 14:15:13 ERROR (Thread-3)] - message not auth: null
[2025-03-16 14:16:29 ERROR (Thread-3)] - message not auth: null
[2025-03-16 15:16:03 ERROR (Thread-3)] - message not auth: null
[2025-03-16 15:32:49 ERROR (Thread-3)] - message not auth: null
[2025-03-16 15:35:03 ERROR (Thread-3)] - message not auth: null
[2025-03-16 15:41:32 ERROR (Thread-3)] - message not auth: null
[2025-03-16 15:51:53 ERROR (Thread-3)] - message not auth: null
[2025-03-16 15:53:29 ERROR (Thread-3)] - message not auth: null
[2025-03-16 16:03:44 ERROR (Thread-3)] - message not auth: null
[2025-03-16 16:08:36 ERROR (Thread-3)] - message not auth: null
[2025-03-16 16:16:46 ERROR (Thread-3)] - message not auth: null
[2025-03-16 16:19:24 ERROR (Thread-3)] - message not auth: null
[2025-03-16 16:27:56 ERROR (Thread-3)] - message not auth: null
[2025-03-16 16:28:35 ERROR (Thread-3)] - message not auth: null
[2025-03-16 17:09:04 ERROR (Thread-1)] - java.net.ConnectException: Connection refused
[2025-03-16 17:20:30 ERROR (Thread-1)] - java.net.ConnectException: Connection refused
[2025-03-16 17:20:34 ERROR (Thread-1)] - java.net.ConnectException: Connection refused
[2025-03-18 10:48:32 ERROR (Thread-1)] - java.net.ConnectException: Connection refused
[2025-03-21 21:39:36 ERROR (JavaFX Application Thread)] - Connection attempt 1 failed: Could not connect to server
[2025-03-21 21:39:36 ERROR (Thread-2)] - java.net.ConnectException: Connection refused
[2025-03-21 21:39:39 ERROR (pool-2-thread-1)] - Connection attempt 2 failed: Could not connect to server
[2025-03-21 21:39:39 ERROR (Thread-3)] - java.net.ConnectException: Connection refused
[2025-03-21 21:39:44 ERROR (pool-2-thread-1)] - Connection attempt 3 failed: Could not connect to server
[2025-03-21 21:39:44 ERROR (Thread-4)] - java.net.ConnectException: Connection refused
[2025-03-21 21:39:54 ERROR (pool-2-thread-1)] - Connection attempt 4 failed: Could not connect to server
[2025-03-21 21:39:54 ERROR (Thread-5)] - java.net.ConnectException: Connection refused
[2025-03-21 21:40:09 ERROR (pool-2-thread-1)] - Connection attempt 5 failed: Could not connect to server
[2025-03-21 21:40:09 ERROR (pool-2-thread-1)] - Failed to connect: java.lang.Exception: Failed to connect after 5 attempts
[2025-03-29 13:25:04 ERROR (JavaFX Application Thread)] - Connection attempt 1 failed: Could not connect to server
[2025-03-29 13:25:07 ERROR (pool-2-thread-1)] - Connection attempt 2 failed: Could not connect to server
[2025-03-29 13:25:12 ERROR (pool-2-thread-1)] - Connection attempt 3 failed: Could not connect to server
[2025-03-29 13:25:12 ERROR (Thread-8)] - doSendMessage err
java.lang.NullPointerException: Cannot invoke "java.io.DataOutputStream.writeByte(int)" because "this.dos" is null
	at org.duynguyen.atttclient@1.0-SNAPSHOT/org.duynguyen.atttclient.network.Session.doSendMessage(Session.java:140) ~[classes/:?]
	at org.duynguyen.atttclient@1.0-SNAPSHOT/org.duynguyen.atttclient.network.Session.doConnect(Session.java:96) ~[classes/:?]
	at org.duynguyen.atttclient@1.0-SNAPSHOT/org.duynguyen.atttclient.network.Session.networkInit(Session.java:75) ~[classes/:?]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
[2025-03-29 13:25:12 ERROR (Thread-8)] - java.lang.NullPointerException: Cannot invoke "org.duynguyen.atttclient.network.IMessageHandler.onConnectOK()" because "this.controller" is null
[2025-03-29 13:26:05 ERROR (JavaFX Application Thread)] - Connection attempt 1 failed: Could not connect to server
[2025-03-29 13:27:05 ERROR (JavaFX Application Thread)] - Connection attempt 1 failed: Could not connect to server
[2025-03-29 13:27:08 ERROR (pool-2-thread-1)] - Connection attempt 2 failed: Could not connect to server
[2025-03-29 13:27:13 ERROR (pool-2-thread-1)] - Connection attempt 3 failed: Could not connect to server
[2025-03-29 13:27:13 ERROR (Thread-8)] - doSendMessage err
java.net.SocketException: Socket closed
	at java.base/sun.nio.ch.NioSocketImpl.endWrite(NioSocketImpl.java:388) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:427) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:445) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:831) ~[?:?]
	at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1035) ~[?:?]
	at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1031) ~[?:?]
	at java.base/java.io.DataOutputStream.writeByte(DataOutputStream.java:158) ~[?:?]
	at org.duynguyen.atttclient@1.0-SNAPSHOT/org.duynguyen.atttclient.network.Session.doSendMessage(Session.java:142) ~[classes/:?]
	at org.duynguyen.atttclient@1.0-SNAPSHOT/org.duynguyen.atttclient.network.Session.doConnect(Session.java:96) ~[classes/:?]
	at org.duynguyen.atttclient@1.0-SNAPSHOT/org.duynguyen.atttclient.network.Session.networkInit(Session.java:75) ~[classes/:?]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
[2025-03-29 13:27:13 ERROR (Thread-8)] - java.lang.NullPointerException: Cannot invoke "org.duynguyen.atttclient.network.IMessageHandler.onConnectOK()" because "this.controller" is null
[2025-03-29 13:27:23 ERROR (pool-2-thread-1)] - Connection attempt 4 failed: Could not connect to server
[2025-03-29 14:52:37 ERROR (JavaFX Application Thread)] - Connection attempt 1 failed: Could not connect to server
[2025-03-29 14:52:40 ERROR (pool-2-thread-1)] - Connection attempt 2 failed: Could not connect to server
[2025-03-29 14:52:45 ERROR (pool-2-thread-1)] - Connection attempt 3 failed: Could not connect to server
[2025-03-29 14:52:55 ERROR (pool-2-thread-1)] - Connection attempt 4 failed: Could not connect to server
[2025-03-29 14:52:55 ERROR (Thread-11)] - doSendMessage err
java.net.SocketException: Broken pipe
	at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:425) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:445) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:831) ~[?:?]
	at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1035) ~[?:?]
	at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1031) ~[?:?]
	at java.base/java.io.DataOutputStream.writeByte(DataOutputStream.java:158) ~[?:?]
	at org.duynguyen.atttclient@1.0-SNAPSHOT/org.duynguyen.atttclient.network.Session.doSendMessage(Session.java:142) ~[classes/:?]
	at org.duynguyen.atttclient@1.0-SNAPSHOT/org.duynguyen.atttclient.network.Session.doConnect(Session.java:97) ~[classes/:?]
	at org.duynguyen.atttclient@1.0-SNAPSHOT/org.duynguyen.atttclient.network.Session.networkInit(Session.java:75) ~[classes/:?]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
[2025-03-29 15:01:04 ERROR (JavaFX Application Thread)] - Failed to connect to server
[2025-03-29 15:01:32 ERROR (Thread-2)] - java.net.ConnectException: Connection refused
[2025-03-29 15:01:32 ERROR (JavaFX Application Thread)] - Failed to connect to server
[2025-03-29 15:04:28 ERROR (Thread-2)] - java.net.ConnectException: Connection refused
[2025-03-29 15:04:33 ERROR (JavaFX Application Thread)] - Connection attempt 1 failed: Connection timed out
[2025-03-29 15:04:36 ERROR (Thread-3)] - java.net.ConnectException: Connection refused
[2025-03-29 15:04:41 ERROR (pool-2-thread-1)] - Connection attempt 2 failed: Connection timed out
[2025-03-29 15:04:46 ERROR (Thread-4)] - java.net.ConnectException: Connection refused
[2025-03-29 15:04:51 ERROR (pool-2-thread-1)] - Connection attempt 3 failed: Connection timed out
[2025-03-29 15:10:50 ERROR (Thread-2)] - java.net.ConnectException: Connection refused
[2025-03-29 15:10:54 ERROR (JavaFX Application Thread)] - Connection attempt 1 failed: Connection timed out
[2025-03-29 15:10:57 ERROR (Thread-4)] - java.net.ConnectException: Connection refused
[2025-03-29 15:11:02 ERROR (pool-2-thread-1)] - Connection attempt 2 failed: Connection timed out
[2025-03-29 15:11:07 ERROR (Thread-6)] - java.net.ConnectException: Connection refused
[2025-03-29 15:11:12 ERROR (pool-2-thread-1)] - Connection attempt 3 failed: Connection timed out
[2025-03-29 16:57:41 ERROR (Thread-2)] - message not auth: Not on FX application thread; currentThread = Thread-2
[2025-03-29 17:01:23 ERROR (Thread-2)] - message not auth: Not on FX application thread; currentThread = Thread-2
[2025-03-29 17:07:20 ERROR (Thread-2)] - message not auth: Not on FX application thread; currentThread = Thread-2
[2025-03-29 17:17:12 ERROR (Thread-2)] - message not auth: Not on FX application thread; currentThread = Thread-2
[2025-03-29 17:22:44 ERROR (ForkJoinPool.commonPool-worker-2)] - java.net.ConnectException: Connection refused
[2025-03-29 17:23:45 ERROR (Thread-2)] - message not auth: Not on FX application thread; currentThread = Thread-2
[2025-03-29 21:00:16 ERROR (ForkJoinPool.commonPool-worker-2)] - java.net.ConnectException: Connection refused
[2025-04-02 23:09:06 ERROR (Thread-4)] - Error decrypting file: null
[2025-04-02 23:12:57 ERROR (Thread-3)] - Error decrypting file: null
[2025-04-02 23:17:04 ERROR (Thread-3)] - Error decrypting file: null
[2025-04-02 23:28:47 ERROR (Thread-3)] - Error decrypting file: null
[2025-04-02 23:30:11 ERROR (Thread-3)] - Error decrypting file: null
[2025-04-02 23:37:53 ERROR (Thread-3)] - Error decrypting file: null
[2025-04-02 23:40:58 ERROR (Thread-3)] - Error decrypting file: null
